### ISSUE TITLE
Path in importer.sh

### ISSUE THREAD

**Issue by Aakashagr** [albanie/mcnPyTorch#1]
Hi albanie,

Sorry for the naive question. I have a VGG16 model trained on pytorch. The model is in pth.tar format. Can you please help me in converting that in matconvnet format. I guess I will have to indicate some path instead of $1, $2, $3 and $4 in the section of the "importer.sh" code below. But not sure what should I point them to. Please do share if you have any example code. Thanks

function convert_model()
{
    pytorch_model=$1
    mcn_model_path=$2
    model_def=$3
    weights=$4
	converter="ipython $SCRIPTPATH/python/import_pytorch.py --"
	mkdir -p "${import_dir}"

**Comment by albanie** [comment]
Hi @aakashiisc, sorry for the slow response.   The values `$1` ...`$4` corresponding the numbering of the input arguments to the function.   To run the converter with your own paths, you could directly write something like:

```
python $SCRIPTPATH/python/import_pytorch.py
                 --image-size='[224,224]' 
                --full-image-size='[256,256]' \
                 --model-def=<path_to_your_model_definition> \
                 --model-weights=<path_to_your_weights> \
                 <model_name> <output_path>
```

where you fill in the `<values>` yourself.  It is quite a fiddly process.  If you are run into difficulties feel free to send me a link to an uploaded copy of your model and I will have a go at importing it.  Good luck!

**Comment by Aakashagr** [comment]
Thanks for the reply, I am planning to import multiple pytorch trained networks into matconvnet. I am trying to see how models weights change over the course of training. So I guess it will be good if I am able to run this script on my PC. 

As per you suggestion I am running this script from mcnPyTorch/python folder. Let me know if there is anything wrong here.  

python import_pytorch.py
                 --image-size='[224,224]' 
                --full-image-size='[256,256]' \
                 --model-def=/usr/local/lib/python3.5/dist-packages/torchvision/models\vgg.py \
                 --model-weights=/home/aakash/Desktop/null_vgg16_bn_epoch_50.pth.tar \
                 vgg_bn /home/aakash/Desktop/


I got an error in pytorch_utils.py "import pretrainedmodels", I guess it was the path issue. I downloaded file from "https://github.com/Cadene/pretrained-models.pytorch#torchvision"  to overcome this issue.
But now I get this error 
...
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'modelsvgg'
 
Any help is appreciated.
Thanks

**Comment by albanie** [comment]
Good job for finding the `pretrainedmodels` code, I forgot to add that as a dependency!  With the import error, my guess is that it is coming from [here](https://github.com/albanie/mcnPyTorch/blob/master/python/pytorch_utils.py#L282).  The idea of using `importlib` is to let you specify the python file containing your network definition.  The code has been updated to give more a more helpful error message. In the mean time, I think the issue might be in your line:

`--model-def=/usr/local/lib/python3.5/dist-packages/torchvision/models\vgg.py `

The last slash looks to be pointing the wrong way, so I don't think it's getting parsed as a path properly.

**Comment by Aakashagr** [comment]
Thanks a lot for the help. It was a stupid mistake I made. I have successfully converted the pytorch model into MATLAB format.  The output .mat file contained " layers, meta and params".  However, format of **layers** differs from the models downloaded from mcn website. Please let me know if something is missing.  Since I used VGG16_bn, I added that in pytorch_utils.py. 

There is a small mistake in pytorch_utils.py, Line 300, it should be    
net = torchvision.models.vgg19(pretrained=True)

**Comment by albanie** [comment]
Good spot for the `pytorch_utils.py` error, I've added a fix.  How does the format differ? If if would be helpful and you could upload the converted model to a public drive/dropbox folder, I could take a look at it?

**Comment by Aakashagr** [comment]
Here is a link to Google Drive, https://drive.google.com/drive/folders/0B9Q1Zqf7ZekJbUNjaGp6QVBXZHM?usp=sharing 

I have uploaded both pytorch model and converted model.

**Comment by albanie** [comment]
I wasn't able to unpack the tar file for some reason, but the matconvnet model seems to run.  This produced outputs for me:

```
tmp = load('/tmp/pt-tmp/vgg16_bn.mat') ;
dag = dagnn.DagNN.loadobj(tmp) ;

% pre-process image
im = single(imread('peppers.png')) ;
im = imresize(im, [224 224]) ;
rgb = permute(dag.meta.normalization.averageImage, [3 2 1]) ;
im = bsxfun(@minus, im, rgb) ;

dag.mode = 'test' ;
dag.eval({'data', im}) ;
scores = dag.vars(end).value ;
[bestScore, best] = max(scores) ;
title(sprintf('(%d), score %.3f', best, bestScore)) ;
```

**Comment by Aakashagr** [comment]
I was trying to run it using vl_simplenn.  Can you please let me which matconvnet version are you using. 
I get the following error while loading the model using dagnn.DagNN.loadobj

Error in dagnn.DagNN.loadobj (line 26)
    block = constr() ;
Undefined function or variable 'dagnn.Permute' and Undefined function or variable 'dagnn.Flatten' 

These are 45th and 46th fields in layers.

**Comment by albanie** [comment]
Yep! Those blocks are in the `matlab` folder of this repo [here](https://github.com/albanie/mcnPyTorch/tree/master/matlab).

**Comment by Aakashagr** [comment]
Thanks a lot albanie  for answering all my questions. It works on my PC as well. However, I am just wondering if it possible to extract features from intermediate layers

**Comment by Aakashagr** [comment]
I think I figured it out. I just need to set the conserve memory flag to 0. Thank you once again
