### ISSUE TITLE
Issue with import pytorch.py

### ISSUE THREAD

**Issue by sumo8291** [albanie/mcnPyTorch#2]
Hi,
I was running the importer.sh code and I am getting this weird error. Could u please help me so that i can mitigate this problem.

Thanks 
I am using python 3.5.2 interpreter in my ubuntu machine

./importer.sh 
Hello Exporting PyTorch model to matconvnet (may take some time) ...
  File "/home/roy030/CVPR2018/matconvnet-1.0-beta24/mcnPyTorch/python/import_pytorch.py", line 93
    merge_name = '{}_merge'.format(name) ; ins = [*id_var, *state['in_vars']]
                                                  ^
SyntaxError: invalid syntax

**Comment by albanie** [comment]
Sorry, somehow I completely missed this :(.  It's probably no longer useful, but will update the code to be more compatible.
